---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: syncwatch
  namespace: argocd
  labels:
    app.kubernetes.io/name: syncwatch
    app.kubernetes.io/part-of: syncwatch
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
  - patch
